export const DEFAULT_ID_DESCRICAO = { id: "*", descricao: "*" };

export const idDescricao = {
  id: 0,
  descricao: "",
};

export const TIPO_SEXO = {
  NAO_INFORMADO: "I",
  FEMININO: "F",
  MASCULINO: "M",
  JURIDICO: "J",
};

export const initialValuesAddress = {
  id: "",
  consumidorId: "",
  tipoEnderecoId: "",
  endereco: "",
  complemento: "",
  bairro: "",
  cep: "",
  paisId: "",
  unidadeFederativaId: "",
  cidadeId: "",
  cnpj: "",
  inscricaoEstadual: "",
  inscricaoMunicipal: "",
  principal: "",
  situacao: "",
  pais: "",
  cidade: "",
  unidadeFederativa: "",
};

export const initialValuesSenha = {
  senhaAntiga: "",
  senhaNova: "",
  usuarioId: "",
};

export const initialValuesConsumer = {
  id: "",
  nascimento: null,
  nome: "",
  nomeFantasia: "",
  tipoId: 0,
  diaNascimento: "",
  mesNascimento: "",
  anoNascimento: "",
  email: "",
  site: "",
  sexo: TIPO_SEXO.NAO_INFORMADO,
  estadoCivilId: 0,
  telefone: "",
  dDDTelefone: "",
  obsTelefone: "",
  celular: "",
  dDDCelular: "",
  obsCelular: "",
  fax: "",
  dDDFax: "",
  obsFax: "",
  dDDWhatsApp: "",
  telefoneWhatsApp: "",
  profissaoId: 0,
  especialidadeId: 0,
  empresa: "",
  cPF: "",
  rG: "",
  cnpj: "",
  inscricaoEstadual: "",
  cRM: "",
  inscricaoMunicipal: "",
  matrizId: "",
  principal: "",
  areaAtuacaoId: 0,
  tipoAreaAtuacaoId: 0,
  subTipoAreaAtuacaoId: "",
  representante: false,
  receberNewsletter: false,
  receberSMS: false,
  prospect: false,
  senha: "",
  obs: "",
  imagem: "",
  usuarioId: "",
  origemId: "",
  enderecos: [],
};
